///General Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM = 10.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_CARD_MEDIUM_3 = 14.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;

const MARGIN_XL_LARGE = 32.0;
const MARGIN_XXL_LARGE = 42.0;
const MARGIN_XXXL_LARGE = 48.0;
const MARGIN_XXXXL_LARGE = 54.0;

const TEXT_SMALL = 12.0;
const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

const BOX_SHADOW_SPEAD_RADIUS = 0.5;
const BOX_SHADOW_BLUR_RADIUS = 15.0;

///App Specific Dimensions
const MOVIE_PAGE_BUTTON_HEIGHT = 55.0;
const PLAY_BUTTON_SIZE = 56.0;
const MOVIE_DETAILS_SCREEN_APP_BAR_HEIGHT = 200.0;
const MOVIE_DETAIL_SCREEN_IMAGE_WIDTH = 150.0;
const MOVIE_DETAIL_SCREEN_IMAGE_HEIGHT = 180.0;
const MOVIE_DETAIL_ACTOR_LISTVIEW_HEIGHT = 120.0;
const MOVIE_DETAIL_ACTOR_VIEW_WIDTH = 60.0;

///Choose Cinema Dimensions
const CHOOSE_CINEMA_LIST_DATE_CARD_HEIGHT = 100.0;
const CHOOSE_CINEMA_DATE_CARD_WIDTH = 70.0;
const FOOD_CARD_BUTTON_WIDTH = 150.0;

///CheckOut
const CHECKOUT_DATE_ITEM_WIDTH = 100.0;

///PROFILE PAGE
const PROFILE_PAGE_SLIVER_APP_BAR_HEIGHT = 200.0;

///SEARCH PAGE
const SEARCH_PAGE_DROPDOWN_WIDTH = 110.0;
const SEARCH_PAGE_DROPDOWN_HEIGHT = 35.0;
