// HIVE TYPE
const int HIVE_TYPE_ID_BANNER_VO = 1;
const int HIVE_TYPE_ID_CHECK_OUT_VO = 2;
const int HIVE_TYPE_ID_CINEMA_AND_TIME_SLOT_VO = 3;
const int HIVE_TYPE_ID_CINEMA_VO = 4;
const int HIVE_TYPE_ID_CITY_VO = 5;
const int HIVE_TYPE_ID_COLLECTION_VO = 6;
const int HIVE_TYPE_ID_CONFIG_VO = 7;
const int HIVE_TYPE_ID_CREDIT_VO = 8;
const int HIVE_TYPE_ID_DATE_VO = 9;
const int HIVE_TYPE_ID_FACILITIES_VO = 10;
const int HIVE_TYPE_ID_GENRE_VO = 11;
const int HIVE_TYPE_ID_MOVIE_VO = 12;
const int HIVE_TYPE_ID_PAYMENT_VO = 13;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 14;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 15;
const int HIVE_TYPE_ID_SNACK_CATEGORY_VO = 16;
const int HIVE_TYPE_ID_SNACK_VO = 17;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 18;
const int HIVE_TYPE_ID_TIME_SLOT_VO = 19;
const int HIVE_TYPE_ID_USER_VO = 20;
const int HIVE_TYPE_ID_CINEMA_LIST_VO = 21;
const int HIVE_TYPE_ID_CREDIT_LIST_VO = 22;

// BOX NAME
const String BOX_NAME_BANNER_VO = 'BOX_NAME_BANNER_VO';
const String BOX_NAME_CHECKOUT_VO = 'BOX_NAME_CHECKOUT_VO';
const String BOX_NAME_CINEMA_AND_TIME_SLOT_VO =
    'BOX_NAME_CINEMA_AND_TIME_SLOT_VO';
const String BOX_NAME_CINEMA_VO = 'BOX_NAME_CINEMA_VO';
const String BOX_NAME_CITY_VO = 'BOX_NAME_CITY_VO';
const String BOX_NAME_COLLECTION_VO = 'BOX_NAME_COLLECTION_VO';
const String BOX_NAME_CONFIG_VO = 'BOX_NAME_CONFIG_VO';
const String BOX_NAME_CREDIT_VO = 'BOX_NAME_CREDIT_VO';
const String BOX_NAME_DATE_VO = 'BOX_NAME_DATE_VO';
const String BOX_NAME_FACILITIES_VO = 'BOX_NAME_FACILITIES_VO';
const String BOX_NAME_GENRE_VO = 'BOX_NAME_GENRE_VO';
const String BOX_NAME_MOVIE_VO = 'BOX_NAME_MOVIE_VO';
const String BOX_NAME_PAYMENT_VO = 'BOX_NAME_PAYMENT_VO';
const String BOX_NAME_PRODUCTION_COMPANY_VO = 'BOX_NAME_PRODUCTION_COMPANY_VO';
const String BOX_NAME_PRODUCTION_COUNTRY_VO = 'BOX_NAME_PRODUCTION_COUNTRY_VO';
const String BOX_NAME_SNACK_CATEGORY_VO = 'BOX_NAME_SNACK_CATEGORY_VO';
const String BOX_NAME_SNACK_VO = 'BOX_NAME_SNACK_VO';
const String BOX_NAME_SPOKEN_LANGUAGE_VO = 'BOX_NAME_SPOKEN_LANGUAGE_VO';
const String BOX_NAME_TIME_SLOT_VO = 'BOX_NAME_TIME_SLOT_VO';
const String BOX_NAME_USER_VO = 'BOX_NAME_USER_VO_VO';
const String BOX_NAME_CINEMA_LIST_VO = 'BOX_NAME_CINEMA_LIST_VO';
const String BOX_NAME_CREDIT_LIST_VO = 'BOX_NAME_CREDIT_LIST_VO';
