// final nowShowingMovieList = [
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
// ];
// final upCommingMovieList = [
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'showingDate': '10th AUG',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'showingDate': '10th AUG',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'showingDate': '10th AUG',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'showingDate': '10th AUG',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'showingDate': '10th AUG',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
//   {
//     'image': 'assets/images/movie_item.png',
//     'name': 'Venom II',
//     'rating': '9.0',
//     'showingDate': '10th AUG',
//     'countryType': 'U/A',
//     'movieType': '2D, 3D, 3D IMAX',
//   },
// ];
